import type { SalesExportRow } from './types'

export const EXPORT_COLUMNS: { key: keyof SalesExportRow; label: string; index: number }[] = [
  { key: 'orderNumber',       label: 'N° Orden',              index: 0 },
  { key: 'orderType',         label: 'Tipo',                  index: 1 },
  { key: 'orderStatusLabel',  label: 'Estado',                index: 2 },
  { key: 'customerName',      label: 'Cliente',               index: 3 },
  { key: 'customerEmail',     label: 'Email',                 index: 4 },
  { key: 'customerPhone',     label: 'Teléfono',              index: 5 },
  { key: 'customerDocumentNumber', label: 'Doc. Identidad',   index: 6 },
  { key: 'storeName',         label: 'Tienda',                index: 7 },
  { key: 'itemsSummary',      label: 'Resumen',               index: 8 },
  { key: 'totalQuantity',     label: 'Unidades',              index: 9 },
  { key: 'productsDetail',    label: 'Detalle Productos',     index: 10 },
  { key: 'servicesDetail',    label: 'Detalle Servicios',     index: 11 },
  { key: 'subtotal',          label: 'Subtotal',              index: 12 },
  { key: 'shippingCost',      label: 'Costo Envío',           index: 13 },
  { key: 'taxAmount',         label: 'Impuestos',             index: 14 },
  { key: 'discountAmount',    label: 'Descuento',             index: 15 },
  { key: 'total',             label: 'Total',                 index: 16 },
  { key: 'couponCode',        label: 'Cupón',                 index: 17 },
  { key: 'paymentMethod',     label: 'Método Pago',           index: 18 },
  { key: 'paymentStatusLabel', label: 'Estado Pago',          index: 19 },
  { key: 'paidAt',            label: 'Fecha Pago',            index: 20 },
  { key: 'shippingType',      label: 'Tipo Envío',            index: 21 },
  { key: 'carrier',           label: 'Transportista',         index: 22 },
  { key: 'trackingNumber',    label: 'Tracking',              index: 23 },
  { key: 'shippingAddress',   label: 'Dirección Envío',       index: 24 },
  { key: 'shippingCity',      label: 'Ciudad',                index: 25 },
  { key: 'shippingNotes',     label: 'Notas Envío',           index: 26 },
  { key: 'customerNotes',     label: 'Notas Cliente',         index: 27 },
  { key: 'createdAt',         label: 'Creado',                index: 28 },
  { key: 'updatedAt',         label: 'Actualizado',           index: 29 },
]

export const EXPORT_EMPTY_ROW: SalesExportRow = {
  orderId: '',
  orderNumber: '',
  orderType: '',
  orderStatus: '',
  orderStatusLabel: '',
  customerName: '',
  customerEmail: '',
  customerPhone: '',
  customerDocumentType: '',
  customerDocumentNumber: '',
  storeName: '',
  itemsSummary: '',
  totalProducts: 0,
  totalServices: 0,
  totalQuantity: 0,
  productsDetail: '',
  servicesDetail: '',
  paymentMethod: '',
  paymentStatus: '',
  paymentStatusLabel: '',
  paidAt: '',
  shippingType: '',
  carrier: '',
  trackingNumber: '',
  shippingAddress: '',
  shippingCity: '',
  shippingPostalCode: '',
  shippingNotes: '',
  subtotal: 0,
  shippingCost: 0,
  taxAmount: 0,
  discountAmount: 0,
  total: 0,
  couponCode: '',
  customerNotes: '',
  createdAt: '',
  updatedAt: '',
}

export const SHIPPING_TYPE_LABELS: Record<string, string> = {
  domicilio: 'Domicilio',
  agencia: 'Agencia',
  retiro_tienda: 'Retiro en Tienda',
}

export const ORDER_TYPE_LABELS: Record<string, string> = {
  product: 'Producto',
  service: 'Servicio',
  mixed: 'Mixto',
}
