sonar.projectKey=lyrium-frontend
#sonar.projectName=Frontend Lyrium
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000

sonar.token=sqp_a29d3beb7ffded964f3750cb168ab59ca0e19139


sonar.sources=frontapp/src

sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**

sonar.sourceEncoding=UTF-8