import {
    LayoutDashboard,
    BarChart3,
    BarChart,
    Store,
    ShoppingBag,
    Users,
    FolderTree,
    Package,
    Boxes,
    Star,
    ShoppingCart,
    RotateCcw,
    Truck,
    CreditCard,
    Percent,
    FileText,
    Settings,
    UserCog,
    Shield,
    Plus,
    TrendingUp,
    TrendingDown,
    Tag,
    Ticket,
    User,
    DollarSign,
    AlertCircle,
    Bell,
    Mail,
    Search,
    Calendar,
    Clock,
    Briefcase,
    Building2,
    Building,
    MapPin,
    Phone,
    Globe,
    Wallet,
    Landmark,
    Receipt,
    ClipboardList,
    LifeBuoy,
    HelpCircle,
    Info,
    CheckCircle2,
    CheckCircle,
    XCircle,
    AlertTriangle,
    Image as LucideImage,
    Trash2,
    Pencil,
    PlusCircle,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ArrowRight,
    ArrowLeft,
    MoreHorizontal,
    MoreVertical,
    LogOut,
    Menu,
    Lightbulb,
    Zap,
    Printer,
    Sparkles,
    Share2,
    Stethoscope,
    CalendarCheck,
    CalendarX,
    ShieldCheck,
    CalendarClock,
    MessageSquare,
    Notebook,
    Instagram,
    Facebook,
    Linkedin,
    Twitter,
    Youtube,
    Contact,
    Camera,
    X,
    Medal,
    Trophy,
    Upload,
    File,
    Eye,
    Heart,
    Check,
    MousePointerClick,
    Map,
    MessageCircle,
    Music,
    Sun,
    Moon,
    Inbox,
    Send,
    CloudUpload,
    Bold,
    Italic,
    Headset,
    Headphones,
    ArrowDown,
    ArrowUp,
    ArrowUpDown,
    MessagesSquare,
    MessageCirclePlus,
    SendHorizontal,
    Banknote,
    Timer,
    Smile,
    Target,
    Gift,
    Home,
    Monitor,
    MonitorPlay,
    AlertOctagon,
    PieChart,
    SearchX,
    ShieldX,
    StarHalf,
    CheckCheck,
    ListChecks,
    RefreshCw,
    Lock,
    Newspaper,
    Flower2,
    LayoutGrid,
    LineChart,
    Coins,
    Award
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';


export const Icons: Record<string, LucideIcon> = {
    LayoutDashboard,
    BarChart3,
    Store,
    Users,
    FolderTree,
    Package,
    Boxes,
    Star,
    ShoppingCart,
    RotateCcw,
    Truck,
    CreditCard,
    Percent,
    FileText,
    Settings,
    UserCog,
    Shield,
    Plus,
    TrendingUp,
    TrendingDown,
    Tag,
    Ticket,
    User,
    DollarSign,
    AlertCircle,
    AlertOctagon,
    Bell,
    Mail,
    Search,
    Calendar,
    Clock,
    Briefcase,
    Building2,
    Building,
    MapPin,
    Phone,
    Globe,
    Wallet,
    Landmark,
    Receipt,
    ClipboardList,
    LifeBuoy,
    HelpCircle,
    Info,
    CheckCircle2,
    CheckCircle,
    XCircle,
    AlertTriangle,
    Image: LucideImage,
    Trash2,
    Pencil,
    PlusCircle,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ArrowRight,
    ArrowLeft,
    MoreHorizontal,
    MoreVertical,
    LogOut,
    Menu,
    Lightbulb,
    Zap,
    Printer,
    Sparkles,
    Share2,
    Stethoscope,
    CalendarCheck,
    CalendarX,
    ShieldCheck,
    CalendarClock,
    MessageSquare,
    Notebook,
    Instagram,
    Facebook,
    Linkedin,
    Twitter,
    Youtube,
    Contact,
    Camera,
    X,
    Medal,
    Trophy,
    Upload,
    File,
    Eye,
    Heart,
    Check,
    MousePointerClick,
    Map,
    MessageCircle,
    Music,
    Sun,
    Moon,
    Inbox,
    Send,
    CloudUpload,
    Bold,
    Italic,
    Headset,
    Headphones,
    ArrowDown,
    ArrowUp,
    ArrowUpDown,
    MessagesSquare,
    MessageCirclePlus,
    SendHorizontal,
    Banknote,
    Timer,
    Smile,
    Target,
    Gift,
    Home,
    Monitor,
    MonitorPlay,
    PieChart,
    SearchX,
    ShieldX,
    StarHalf,
    CheckCheck,
    ListChecks,
    RefreshCw,
    Lock,
    Newspaper,
    Flower2,
    LayoutGrid,
    LineChart,
    Coins,
    Award,
    ShoppingBag,
    UserCircle: User,
    ShoppingCartSimple: ShoppingCart,
    Storefront: Store,
    Buildings: Building2,
    PhoneCall: Phone,
    EnvelopeSimple: Mail,
    ChatCircle: MessageCircle,
    WhatsAppLogo: MessageCircle,
    TiktokLogo: MessageCircle,
    LockKey: Lock,
    ChatCircleDots: MessagesSquare,
    ChatCircleText: MessagesSquare,
    PaperPlaneTilt: SendHorizontal,
    PaperPlaneRight: SendHorizontal,
    Logistics: Truck,
    Shop: Store,
    Inventory: Boxes,
    Finance: DollarSign,
    Sales: ShoppingCart,
    BarChart,
    Services: Briefcase,
    Catalog: Package,
    Help: HelpCircle,
    Messages: MessageSquare,
    Invoices: Receipt,
};

interface IconProps {
    name: string;
    className?: string;
    style?: React.CSSProperties;
}

export default function BaseIcon({ name, className, style }: IconProps) {
    const IconComponent = Icons[name];

    if (!IconComponent) {
        return null;
    }

    return <IconComponent className={className} style={style} />;
}
