import { Order, SalesKPI } from './types';

export const MOCK_ORDERS: Order[] = [
    {
        id: '1',
        orderNumber: 'ORD-001',
        statusLabel: 'Preparando',
        fecha: '2024-03-15',
        updatedAt: '2024-03-16T14:30:00',
        cliente: 'Ana Martínez',
        customerEmail: 'ana@example.com',
        customerPhone: '999888777',
        customerDocument: '76543210',
        customerDocumentType: 'DNI',
        dni: '76543210',
        subtotal: 250.50,
        shippingCost: 15.00,
        taxAmount: 0,
        discountAmount: 0,
        total: 265.50,
        unidades: 3,
        estado: 'processing',
        global_status: 'processing',
        currentStep: 2,
        productCurrentStep: 2,
        serviceCurrentStep: 0,
        orderType: 'product',
        itemsSummary: 'Producto A, Producto B',
        paymentStatusLabel: 'Verificado',
        tipo_envio: 'domicilio',
        metodo_pago: 'Tarjeta de Crédito',
        estado_pago: 'verificado',
        trackingNumber: 'TRK-123456789',
        storeName: 'Mi Tienda',
        couponCode: null,
        notes: null,
        paidAt: '2024-03-15T14:00:00Z',
        envio: { direccion: 'Av. Siempre Viva 123, Lima', carrier: 'Olva Courier', tracking: 'TRK-123456789', costo: 15.00, city: 'Lima', postalCode: '15001', notes: '' },
        items: [
            { id: '1', storeId: 1, isOwn: true, name: 'Producto A', qty: 2, price: 100.00, lineTotal: 200.00, shippingCost: 0, status: 'confirmed', can_confirm: false, can_cancel: false },
            { id: '2', storeId: 1, isOwn: true, name: 'Producto B', qty: 1, price: 50.50, lineTotal: 50.50, shippingCost: 0, status: 'processing', can_confirm: false, can_cancel: false }
        ],
        serviceItems: []
    },
    {
        id: '2',
        orderNumber: 'ORD-002',
        statusLabel: 'Pendiente Confirmar',
        fecha: '2024-03-16',
        updatedAt: '2024-03-16T10:00:00',
        cliente: 'Roberto Gómez',
        customerEmail: 'roberto@example.com',
        customerPhone: '888777666',
        customerDocument: '01234567',
        customerDocumentType: 'DNI',
        dni: '01234567',
        subtotal: 89.90,
        shippingCost: 10.00,
        taxAmount: 0,
        discountAmount: 0,
        total: 99.90,
        unidades: 1,
        estado: 'pending_seller',
        global_status: 'pending_seller',
        currentStep: 1,
        productCurrentStep: 0,
        serviceCurrentStep: 1,
        orderType: 'service',
        itemsSummary: 'Consulta Veterinaria',
        paymentStatusLabel: 'Verificado',
        tipo_envio: 'agencia',
        metodo_pago: 'Yape',
        estado_pago: 'verificado',
        trackingNumber: 'SHL-987654321',
        storeName: 'Mi Tienda',
        couponCode: null,
        notes: 'Prefiero atención en la mañana',
        paidAt: '2024-03-16T09:30:00Z',
        envio: { direccion: 'Calle Falsa 456, Arequipa', carrier: 'Shalom', tracking: 'SHL-987654321', costo: 10.00, city: 'Arequipa', postalCode: '04001', notes: 'Dejar en portería' },
        items: [],
        serviceItems: [
            {
                id: 's1',
                serviceId: 101,
                serviceName: 'Consulta Veterinaria',
                storeId: 1,
                storeName: 'Mi Tienda',
                specialistName: 'Dr. Pérez',
                quantity: 1,
                unitPrice: 89.90,
                lineTotal: 89.90,
                status: 'pending_seller',
                appointmentDate: '2024-03-20',
                startTime: '10:00:00',
                endTime: '11:00:00',
                modality: 'presencial',
                durationMinutes: 60,
                serviceBookingId: 'bk-001'
            }
        ]
    },
    {
        id: '3',
        orderNumber: 'ORD-003',
        statusLabel: 'Pendiente Confirmar',
        fecha: '2024-03-17',
        updatedAt: '2024-03-17T08:00:00',
        cliente: 'Carmen Rojas',
        customerEmail: 'carmen@example.com',
        customerPhone: '777666555',
        customerDocument: '44556677',
        customerDocumentType: 'DNI',
        dni: '44556677',
        subtotal: 450.00,
        shippingCost: 20.00,
        taxAmount: 0,
        discountAmount: 0,
        total: 470.00,
        unidades: 5,
        estado: 'pending_seller',
        global_status: 'pending_seller',
        currentStep: 1,
        productCurrentStep: 0,
        serviceCurrentStep: 0,
        orderType: 'mixed',
        itemsSummary: 'Producto D, Corte de Cabello',
        paymentStatusLabel: 'Pendiente',
        tipo_envio: 'domicilio',
        metodo_pago: 'Transferencia Bancaria',
        estado_pago: 'pendiente',
        trackingNumber: '-',
        storeName: 'Mi Tienda',
        couponCode: null,
        notes: null,
        paidAt: null,
        envio: { direccion: 'Urb. Los Rosales Mz A Lt 5, Trujillo', carrier: 'Shalom', tracking: 'SHL-9876543456', costo: 20.00, city: 'Trujillo', postalCode: '13001', notes: '' },
        items: [
            { id: '4', storeId: 1, isOwn: true, name: 'Producto D', qty: 5, price: 90.00, lineTotal: 450.00, shippingCost: 0, status: 'pending_seller', can_confirm: true, can_cancel: true }
        ],
        serviceItems: [
            {
                id: 's2',
                serviceId: 102,
                serviceName: 'Corte de Cabello',
                storeId: 1,
                storeName: 'Mi Tienda',
                specialistName: 'María López',
                quantity: 1,
                unitPrice: 30.00,
                lineTotal: 30.00,
                status: 'pending_seller',
                appointmentDate: null,
                startTime: null,
                endTime: null,
                modality: 'domicilio',
                durationMinutes: 45,
                serviceBookingId: 'bk-002'
            }
        ]
    }
];

export const MOCK_KPIS: SalesKPI[] = [
    { label: 'Ingresos Mensuales', count: 45000, status: 'Total', icon: 'Finance', color: 'sky' },
    { label: 'Nuevos Pedidos', count: 12, status: 'Pendientes', icon: 'Sales', color: 'indigo' },
    { label: 'En Preparación', count: 5, status: 'Agencia', icon: 'Catalog', color: 'cyan' },
    { label: 'En Camino', count: 8, status: 'Tránsito', icon: 'Logistics', color: 'amber' },
    { label: 'Devoluciones', count: 1, status: 'Alerta', icon: 'RotateCcw', color: 'red' }
];
