export interface Provincia {
  nombre: string;
  distritos: string[];
}

export interface Departamento {
  nombre: string;
  provincias: Provincia[];
}

export const UBIGEO: Departamento[] = [
  {
    nombre: 'Amazonas',
    provincias: [
      {
        nombre: 'Chachapoyas',
        distritos: [
          'Chachapoyas',
          'Asunción',
          'Balsas',
          'Cheto',
          'Chiliquin',
          'Chuquibamba',
          'Granada',
          'Huancas',
          'La Jalca',
          'Leimebamba',
          'Levanto',
          'Magdalena',
          'Mariscal Castilla',
          'Molinopampa',
          'Montevideo',
          'Olleros',
          'Quinjalca',
          'San Francisco de Daguas',
          'San Isidro de Maino',
          'Soloco',
          'Sonche',
        ],
      },
      {
        nombre: 'Bagua',
        distritos: [
          'Bagua',
          'Aramango',
          'Copallin',
          'El Parco',
          'Imaza',
          'La Peca',
        ],
      },
      {
        nombre: 'Bongará',
        distritos: [
          'Jumbilla',
          'Chisquilla',
          'Churuja',
          'Corosha',
          'Cuispes',
          'Florida',
          'Jazan',
          'Recta',
          'San Carlos',
          'Shipasbamba',
          'Valera',
          'Yambrasbamba',
        ],
      },
      {
        nombre: 'Condorcanqui',
        distritos: [
          'Nieva',
          'El Cenepa',
          'Río Santiago',
        ],
      },
      {
        nombre: 'Luya',
        distritos: [
          'Lamud',
          'Camporredondo',
          'Cocabamba',
          'Colcamar',
          'Conila',
          'Inguilpata',
          'Longuita',
          'Lonya Chico',
          'Luya',
          'Luya Viejo',
          'María',
          'Ocalli',
          'Ocumal',
          'Pisuquia',
          'Providencia',
          'San Cristóbal',
          'San Francisco del Yeso',
          'San Jerónimo',
          'San Juan de Lopecancha',
          'Santa Catalina',
          'Santo Tomas',
          'Tingo',
          'Trita',
        ],
      },
      {
        nombre: 'Rodríguez de Mendoza',
        distritos: [
          'San Nicolás',
          'Chirimoto',
          'Cochamal',
          'Huambo',
          'Limabamba',
          'Longar',
          'Mariscal Benavides',
          'Milpuc',
          'Omia',
          'Santa Rosa',
          'Totora',
          'Vista Alegre',
        ],
      },
      {
        nombre: 'Utcubamba',
        distritos: [
          'Bagua Grande',
          'Cajaruro',
          'Cumba',
          'El Milagro',
          'Jamalca',
          'Lonya Grande',
          'Yamon',
        ],
      },
    ],
  },
  {
    nombre: 'Áncash',
    provincias: [
      {
        nombre: 'Huaraz',
        distritos: [
          'Huaraz',
          'Cochabamba',
          'Colcabamba',
          'Huanchay',
          'Independencia',
          'Jangas',
          'La Libertad',
          'Olleros',
          'Pampas',
          'Pariacoto',
          'Pira',
          'Tarica',
        ],
      },
      {
        nombre: 'Aija',
        distritos: [
          'Aija',
          'Coris',
          'Huacllan',
          'La Merced',
          'Succha',
        ],
      },
      {
        nombre: 'Antonio Raymondi',
        distritos: [
          'Llamellin',
          'Aczo',
          'Chaccho',
          'Chingas',
          'Mirgas',
          'San Juan de Rontoy',
        ],
      },
      {
        nombre: 'Asunción',
        distritos: [
          'Chacas',
          'Acochaca',
        ],
      },
      {
        nombre: 'Bolognesi',
        distritos: [
          'Chiquian',
          'Abelardo Pardo Lezameta',
          'Antonio Raymondi',
          'Aquia',
          'Cajacay',
          'Canis',
          'Colquioc',
          'Huallanca',
          'Huasta',
          'Huayllacayan',
          'La Primavera',
          'Mangas',
          'Pacllon',
          'San Miguel de Corpanqui',
          'Ticllos',
        ],
      },
      {
        nombre: 'Carhuaz',
        distritos: [
          'Carhuaz',
          'Acopampa',
          'Amashca',
          'Anta',
          'Ataquero',
          'Marcara',
          'Pariahuanca',
          'San Miguel de Aco',
          'Shilla',
          'Tinco',
          'Yungar',
        ],
      },
      {
        nombre: 'Carlos Fermín Fitzcarrald',
        distritos: [
          'San Luis',
          'San Nicolás',
          'Yauya',
        ],
      },
      {
        nombre: 'Casma',
        distritos: [
          'Casma',
          'Buena Vista Alta',
          'Comandante Noel',
          'Yautan',
        ],
      },
      {
        nombre: 'Corongo',
        distritos: [
          'Corongo',
          'Aco',
          'Bambamarca',
          'Cusca',
          'La Pampa',
          'Yanac',
          'Yupan',
        ],
      },
      {
        nombre: 'Huari',
        distritos: [
          'Huari',
          'Anra',
          'Cajay',
          'Chavin de Huantar',
          'Huacachi',
          'Huacchis',
          'Huachis',
          'Huantar',
          'Masin',
          'Paucas',
          'Ponto',
          'Rahuapampa',
          'Rapayan',
          'San Marcos',
          'San Pedro de Chana',
          'Uco',
        ],
      },
      {
        nombre: 'Huarmey',
        distritos: [
          'Huarmey',
          'Cochapeti',
          'Culebras',
          'Huayan',
          'Malvas',
        ],
      },
      {
        nombre: 'Huaylas',
        distritos: [
          'Caraz',
          'Huallanca',
          'Huata',
          'Huaylas',
          'Mato',
          'Pamparomas',
          'Pueblo Libre',
          'Santa Cruz',
          'Santo Domingo',
          'Yungay',
        ],
      },
      {
        nombre: 'Mariscal Luzuriaga',
        distritos: [
          'Piscobamba',
          'Casca',
          'Eleazar Guzmán Barron',
          'Fidel Olivas Escudero',
          'Llama',
          'Llumpa',
          'Lucma',
          'Musga',
        ],
      },
      {
        nombre: 'Ocros',
        distritos: [
          'Ocros',
          'Acas',
          'Cajamarquilla',
          'Carhuapampa',
          'Cochas',
          'Congas',
          'Llipa',
          'San Cristóbal de Rajan',
          'San Pedro',
          'Santiago de Chilcas',
        ],
      },
      {
        nombre: 'Pallasca',
        distritos: [
          'Cabana',
          'Bolognesi',
          'Conchucos',
          'Huacaschuque',
          'Huandoval',
          'Lacabamba',
          'Llapo',
          'Pallasca',
          'Pampas',
          'Santa Rosa',
          'Tauca',
        ],
      },
      {
        nombre: 'Pomabamba',
        distritos: [
          'Pomabamba',
          'Huayllan',
          'Parobamba',
          'Quinuabamba',
        ],
      },
      {
        nombre: 'Recuay',
        distritos: [
          'Recuay',
          'Catac',
          'Cotaparaco',
          'Huayllapampa',
          'Llacllin',
          'Marca',
          'Pampas Chico',
          'Pararin',
          'Tapacocha',
          'Ticapampa',
        ],
      },
      {
        nombre: 'Santa',
        distritos: [
          'Chimbote',
          'Caceres del Peru',
          'Coishco',
          'Macate',
          'Moro',
          'Nepeña',
          'Samanco',
          'Santa',
          'Nuevo Chimbote',
        ],
      },
      {
        nombre: 'Sihuas',
        distritos: [
          'Sihuas',
          'Acobamba',
          'Alfonso Ugarte',
          'Cashapampa',
          'Chingalpo',
          'Huayllabamba',
          'Quiches',
          'Ragash',
          'San Juan',
          'Sicsibamba',
        ],
      },
      {
        nombre: 'Yungay',
        distritos: [
          'Yungay',
          'Cascapara',
          'Mancos',
          'Matacoto',
          'Quillo',
          'Ranrahirca',
          'Shupluy',
          'Yanama',
        ],
      },
    ],
  },
  {
    nombre: 'Apurímac',
    provincias: [
      {
        nombre: 'Abancay',
        distritos: [
          'Abancay',
          'Chacoche',
          'Circa',
          'Curahuasi',
          'Huanipaca',
          'Lambrama',
          'Pichirhua',
          'San Pedro de Cachora',
          'Tamburco',
        ],
      },
      {
        nombre: 'Andahuaylas',
        distritos: [
          'Andahuaylas',
          'Andarapa',
          'Chiara',
          'Huancarama',
          'Huancaray',
          'Huayana',
          'Kishuara',
          'Pacobamba',
          'Pacucha',
          'Pampachiri',
          'Pomacocha',
          'San Antonio de Cachi',
          'San Jerónimo',
          'San Miguel de Chaccrampa',
          'Santa María de Chicmo',
          'Talavera',
          'Tumay Huaraca',
          'Turpo',
          'Kaquiabamba',
          'José María Arguedas',
        ],
      },
      {
        nombre: 'Antabamba',
        distritos: [
          'Antabamba',
          'El Oro',
          'Huaquirca',
          'Juan Espinoza Medrano',
          'Oropesa',
          'Pachaconas',
          'Sabaino',
        ],
      },
      {
        nombre: 'Aymaraes',
        distritos: [
          'Chalhuanca',
          'Capaya',
          'Caraybamba',
          'Chapimarca',
          'Colcabamba',
          'Cotaruse',
          'Huayllo',
          'Justo Apu Sahuaraura',
          'Lucre',
          'Pocohuanca',
          'San Juan de Chacña',
          'Sañayca',
          'Soraya',
          'Taparqa',
          'Tintay',
          'Toraya',
          'Yanaca',
        ],
      },
      {
        nombre: 'Chincheros',
        distritos: [
          'Chincheros',
          'Anco_Huallo',
          'Cocharcas',
          'Huaccana',
          'Ocobamba',
          'Ongoy',
          'Uranmarca',
          'Ranracancha',
          'Rocchacc',
          'El Porvenir',
          'Los Chankas',
        ],
      },
      {
        nombre: 'Cotabambas',
        distritos: [
          'Tambobamba',
          'Cotabambas',
          'Coyllurqui',
          'Haquira',
          'Mara',
          'Challhuahuacho',
        ],
      },
      {
        nombre: 'Grau',
        distritos: [
          'Chuquibambilla',
          'Curpahuasi',
          'Gamarra',
          'Huayllati',
          'Mamara',
          'Micaela Bastidas',
          'Pataypampa',
          'Progreso',
          'San Antonio',
          'Santa Rosa',
          'Turpay',
          'Vilcabamba',
          'Virundo',
          'Curasco',
        ],
      },
    ],
  },
  {
    nombre: 'Arequipa',
    provincias: [
      {
        nombre: 'Arequipa',
        distritos: [
          'Arequipa',
          'Alto Selva Alegre',
          'Cayma',
          'Cerro Colorado',
          'Characato',
          'Chiguata',
          'Jacobo Hunter',
          'José Luis Bustamante y Rivero',
          'La Joya',
          'Mariano Melgar',
          'Miraflores',
          'Mollebaya',
          'Paucarpata',
          'Pocsi',
          'Polobaya',
          'Quequeña',
          'Sabandía',
          'Sachaca',
          'San Juan de Siguas',
          'San Juan de Tarucani',
          'Santa Isabel de Siguas',
          'Santa Rita de Siguas',
          'Socabaya',
          'Tiabaya',
          'Uchumayo',
          'Vitor',
          'Yanahuara',
          'Yarabamba',
          'Yura',
          'José María Bustamante',
        ],
      },
      {
        nombre: 'Camaná',
        distritos: [
          'Camaná',
          'José María Quimper',
          'Mariano Nicolás Valcárcel',
          'Mariscal Cáceres',
          'Nicolás de Piérola',
          'Ocoña',
          'Quilca',
          'Samuel Pastor',
        ],
      },
      {
        nombre: 'Caravelí',
        distritos: [
          'Caravelí',
          'Acarí',
          'Atico',
          'Atiquipa',
          'Bella Unión',
          'Cahuacho',
          'Chala',
          'Chaparra',
          'Huanuhuanu',
          'Jaqui',
          'Lomas',
          'Quicacha',
          'Yauca',
        ],
      },
      {
        nombre: 'Castilla',
        distritos: [
          'Aplao',
          'Andagua',
          'Ayo',
          'Chachas',
          'Chilcaymarca',
          'Choco',
          'Huancarqui',
          'Machaguay',
          'Orcopampa',
          'Pampacolca',
          'Tipan',
          'Uñon',
          'Uraca',
          'Viraco',
        ],
      },
      {
        nombre: 'Caylloma',
        distritos: [
          'Chivay',
          'Achoma',
          'Cabanaconde',
          'Callalli',
          'Caylloma',
          'Coporaque',
          'Huambo',
          'Huanca',
          'Ichupampa',
          'Lari',
          'Lluta',
          'Maca',
          'Madrigal',
          'Majocs',
          'San Antonio de Chuca',
          'Sibayo',
          'Tapay',
          'Tisco',
          'Tuti',
          'Yanque',
        ],
      },
      {
        nombre: 'Condesuyos',
        distritos: [
          'Chuquibamba',
          'Andaray',
          'Cayarani',
          'Chichas',
          'Iray',
          'Río Grande',
          'Salamanca',
          'Yanaquihua',
        ],
      },
      {
        nombre: 'Islay',
        distritos: [
          'Mollendo',
          'Cocachacra',
          'Dean Valdivia',
          'Islay',
          'Mejia',
          'Punta de Bombón',
        ],
      },
      {
        nombre: 'La Unión',
        distritos: [
          'Cotahuasi',
          'Alca',
          'Charcana',
          'Huaynacotas',
          'Pampamarca',
          'Puyca',
          'Quechualla',
          'Sayla',
          'Tauria',
          'Tomepampa',
          'Toro',
        ],
      },
    ],
  },
  {
    nombre: 'Ayacucho',
    provincias: [
      {
        nombre: 'Huamanga',
        distritos: [
          'Ayacucho',
          'Acocro',
          'Acos Vinchos',
          'Carmen Alto',
          'Chiara',
          'Nueve de Julio',
          'Ocros',
          'Pacaycasa',
          'Quinua',
          'San José de Ticllas',
          'San Juan Bautista',
          'Santiago de Pischa',
          'Socos',
          'Tambillo',
          'Vinchos',
          'Jesús Nazareno',
          'Andrés Avelino Cáceres Dorregaray',
        ],
      },
      {
        nombre: 'Cangallo',
        distritos: [
          'Cangallo',
          'Chuschi',
          'Los Morochucos',
          'María Parado de Bellido',
          'Paras',
          'Totos',
        ],
      },
      {
        nombre: 'Huanca Sancos',
        distritos: [
          'Huanca Sancos',
          'Carapo',
          'Sacsamarca',
          'Santiago de Lucanamarca',
        ],
      },
      {
        nombre: 'Huanta',
        distritos: [
          'Huanta',
          'Ayahuanco',
          'Huamanguilla',
          'Iguain',
          'Luricocha',
          'Santillana',
          'Sivia',
          'Llochegua',
          'Canayre',
          'Uchuraccay',
          'Pucacolpa',
          'Chaca',
        ],
      },
      {
        nombre: 'La Mar',
        distritos: [
          'San Miguel',
          'Anco',
          'Ayna',
          'Chilcas',
          'Chungui',
          'Luis Carranza',
          'Santa Rosa',
          'Tambo',
          'Samugari',
          'Anchihuay',
          'Oronccoy',
        ],
      },
      {
        nombre: 'Lucanas',
        distritos: [
          'Puquio',
          'Aucara',
          'Cabana',
          'Carmen Salcedo',
          'Chaviña',
          'Chipao',
          'Huac-Huas',
          'Laramate',
          'Leoncio Prado',
          'Llauta',
          'Lucanas',
          'Ocaña',
          'Otoca',
          'Saisa',
          'San Cristóbal',
          'San Juan',
          'San Pedro',
          'San Pedro de Palco',
          'Sancos',
          'Santa Ana de Huaycahuacho',
          'Santa Lucia',
        ],
      },
      {
        nombre: 'Parinacochas',
        distritos: [
          'Coracora',
          'Chumpi',
          'Coronel Castañeda',
          'Pacapausa',
          'Pullo',
          'Puyusca',
          'San Francisco de Ravacayco',
          'Upahuacho',
        ],
      },
      {
        nombre: 'Páucar del Sara Sara',
        distritos: [
          'Pausa',
          'Colta',
          'Corculla',
          'Lampa',
          'Marcabamba',
          'Oyolo',
          'Pararca',
          'San Javier de Alpabamba',
          'San José de Ushua',
          'Sara Sara',
        ],
      },
      {
        nombre: 'Sucre',
        distritos: [
          'Querobamba',
          'Belén',
          'Chalcos',
          'Chilcayoc',
          'Huacaña',
          'Morcolla',
          'Paico',
          'San Pedro de Larcay',
          'San Salvador de Quije',
          'Santiago de Paucaray',
          'Soras',
        ],
      },
      {
        nombre: 'Víctor Fajardo',
        distritos: [
          'Huancapi',
          'Alcamenca',
          'Apongo',
          'Asquipata',
          'Canaria',
          'Cayara',
          'Colca',
          'Huamanquiquia',
          'Huancaraylla',
          'Huaya',
          'Sarhua',
          'Vilcanchos',
        ],
      },
      {
        nombre: 'Vilcas Huamán',
        distritos: [
          'Vilcas Huamán',
          'Accomarca',
          'Carhuanca',
          'Concepción',
          'Huambalpa',
          'Independencia',
          'Saurama',
          'Vischongo',
        ],
      },
    ],
  },
  {
    nombre: 'Cajamarca',
    provincias: [
      {
        nombre: 'Cajamarca',
        distritos: [
          'Cajamarca',
          'Asunción',
          'Chetilla',
          'Cospan',
          'Encañada',
          'Jesús',
          'Llacanora',
          'Los Baños del Inca',
          'Magdalena',
          'Matara',
          'Namora',
          'San Juan',
        ],
      },
      {
        nombre: 'Cajabamba',
        distritos: [
          'Cajabamba',
          'Cachachi',
          'Condebamba',
          'Sitacocha',
        ],
      },
      {
        nombre: 'Celendín',
        distritos: [
          'Celendín',
          'Chumuch',
          'Cortegana',
          'Huasmin',
          'Jorge Chávez',
          'Jose Galvez',
          'Miguel Iglesias',
          'Oxamarca',
          'Sorochuco',
          'Sucre',
          'Utco',
          'La Libertad de Pallan',
        ],
      },
      {
        nombre: 'Chota',
        distritos: [
          'Chota',
          'Anguia',
          'Chadin',
          'Chalamarca',
          'Chiguirip',
          'Chimban',
          'Choropampa',
          'Cochabamba',
          'Conchan',
          'Huambos',
          'Lajas',
          'Llama',
          'Miracosta',
          'Paccha',
          'Pion',
          'Querocoto',
          'San Juan de Licupis',
          'Tacabamba',
          'Tocmoche',
          'San Martín de Chalasia',
        ],
      },
      {
        nombre: 'Contumazá',
        distritos: [
          'Contumazá',
          'Chilete',
          'Cupisnique',
          'Guzmango',
          'San Benito',
          'Santa Cruz de Toled',
          'Tantarica',
          'Yonan',
        ],
      },
      {
        nombre: 'Cutervo',
        distritos: [
          'Cutervo',
          'Callayuc',
          'Choros',
          'Cujillo',
          'La Ramada',
          'Pimpingos',
          'Querocotillo',
          'San Andrés de Cutervo',
          'San Juan de Cutervo',
          'San Luis de Lucma',
          'Santa Cruz',
          'Santo Domingo de La Capilla',
          'Santo Tomas',
          'Socota',
          'Toribio Casanova',
        ],
      },
      {
        nombre: 'Hualgayoc',
        distritos: [
          'Bambamarca',
          'Chugur',
          'Hualgayoc',
        ],
      },
      {
        nombre: 'Jaén',
        distritos: [
          'Jaén',
          'Bellavista',
          'Chontali',
          'Colasay',
          'Huabal',
          'Las Pirias',
          'Pomahuaca',
          'Pucara',
          'Sallique',
          'San Felipe',
          'San José del Alto',
          'Santa Rosa',
        ],
      },
      {
        nombre: 'San Ignacio',
        distritos: [
          'San Ignacio',
          'Chirinos',
          'Huarango',
          'La Coipa',
          'Namballe',
          'San José de Lourdes',
          'Tabaconas',
        ],
      },
      {
        nombre: 'San Marcos',
        distritos: [
          'Pedro Gálvez',
          'Chancay',
          'Eduardo Villanueva',
          'Gregorio Pita',
          'Ichocan',
          'Jose Manuel Quiroz',
          'Jose Sabogal',
        ],
      },
      {
        nombre: 'San Miguel',
        distritos: [
          'San Miguel',
          'Bolivar',
          'Calquis',
          'Catilluc',
          'El Prado',
          'La Florida',
          'Llapa',
          'Nanchoc',
          'Niepos',
          'San Gregorio',
          'San Silvestre de Cochan',
          'Tongod',
          'Union Agua Blanca',
        ],
      },
      {
        nombre: 'San Pablo',
        distritos: [
          'San Pablo',
          'San Bernardino',
          'San Luis',
          'Tumbaden',
        ],
      },
      {
        nombre: 'Santa Cruz',
        distritos: [
          'Santa Cruz',
          'Andabamba',
          'Catache',
          'Chancaybaños',
          'La Esperanza',
          'Ninabamba',
          'Pulan',
          'Saucepampa',
          'Sexi',
          'Uticyacu',
          'Yauyucan',
        ],
      },
    ],
  },
  {
    nombre: 'Callao',
    provincias: [
      {
        nombre: 'Callao',
        distritos: [
          'Callao',
          'Bellavista',
          'Carmen de La Legua',
          'La Perla',
          'La Punta',
          'Ventanilla',
          'Mi Perú',
        ],
      },
    ],
  },
  {
    nombre: 'Cusco',
    provincias: [
      {
        nombre: 'Cusco',
        distritos: [
          'Cusco',
          'Ccorca',
          'Poroy',
          'San Jerónimo',
          'San Sebastian',
          'Santiago',
          'Saylla',
          'Wanchaq',
        ],
      },
      {
        nombre: 'Acomayo',
        distritos: [
          'Acomayo',
          'Acopia',
          'Acos',
          'Mosoc Llacta',
          'Pomacanchi',
          'Rondocan',
          'Sangarara',
        ],
      },
      {
        nombre: 'Anta',
        distritos: [
          'Anta',
          'Ancahuasi',
          'Cachimayo',
          'Chinchaypujio',
          'Huarocondo',
          'Limatambo',
          'Mollepata',
          'Pucyura',
          'Zurite',
        ],
      },
      {
        nombre: 'Calca',
        distritos: [
          'Calca',
          'Coya',
          'Lamay',
          'Lares',
          'Pisac',
          'San Salvador',
          'Taray',
          'Yanatile',
        ],
      },
      {
        nombre: 'Canas',
        distritos: [
          'Yanaoca',
          'Checca',
          'Kunturkanki',
          'Langui',
          'Layo',
          'Pampamarca',
          'Quehue',
          'Tupac Amaru',
        ],
      },
      {
        nombre: 'Canchis',
        distritos: [
          'Sicuani',
          'Checacupe',
          'Combapata',
          'Marangani',
          'Pitumarca',
          'San Pablo',
          'San Pedro',
          'Tinta',
        ],
      },
      {
        nombre: 'Chumbivilcas',
        distritos: [
          'Santo Tomas',
          'Capacmarca',
          'Chamaca',
          'Colquemarca',
          'Livitaca',
          'Llusco',
          'Quiñota',
          'Velille',
        ],
      },
      {
        nombre: 'Espinar',
        distritos: [
          'Espinar',
          'Condoroma',
          'Coporaque',
          'Ocoruro',
          'Pallpata',
          'Pichigua',
          'Suyckutambo',
          'Alto Pichigua',
        ],
      },
      {
        nombre: 'La Convención',
        distritos: [
          'Santa Ana',
          'Echarate',
          'Huayopata',
          'Maranura',
          'Ocobamba',
          'Quellouno',
          'Kimbiri',
          'Santa Teresa',
          'Vilcabamba',
          'Pichari',
          'Inkawasi',
          'Villa Virgen',
          'Villa Kintiarina',
          'Megantoni',
        ],
      },
      {
        nombre: 'Paruro',
        distritos: [
          'Paruro',
          'Accha',
          'Ccapi',
          'Colcha',
          'Huanoquite',
          'Omacha',
          'Paccaritambo',
          'Pillpinto',
          'Yaurisque',
        ],
      },
      {
        nombre: 'Paucartambo',
        distritos: [
          'Paucartambo',
          'Caicay',
          'Challabamba',
          'Colquepata',
          'Huancarani',
          'Kosñipata',
        ],
      },
      {
        nombre: 'Quispicanchi',
        distritos: [
          'Urcos',
          'Andahuaylillas',
          'Camanti',
          'Ccarhuayo',
          'Ccatca',
          'Cusipata',
          'Huaro',
          'Lucre',
          'Marcapata',
          'Ocongate',
          'Oropesa',
          'Quiquijana',
        ],
      },
      {
        nombre: 'Urubamba',
        distritos: [
          'Urubamba',
          'Chinchero',
          'Huayllabamba',
          'Machupicchu',
          'Maras',
          'Ollantaytambo',
          'Yucay',
        ],
      },
    ],
  },
  {
    nombre: 'Huancavelica',
    provincias: [
      {
        nombre: 'Huancavelica',
        distritos: [
          'Huancavelica',
          'Acobambilla',
          'Acoria',
          'Conayca',
          'Cuenca',
          'Huachocolpa',
          'Huayllahuara',
          'Izcuchaca',
          'Laria',
          'Manta',
          'Mariscal Cáceres',
          'Moya',
          'Nuevo Occoro',
          'Palca',
          'Pilchaca',
          'Vilca',
          'Yauli',
          'Ascensión',
          'Huando',
        ],
      },
      {
        nombre: 'Acobamba',
        distritos: [
          'Acobamba',
          'Andabamba',
          'Anta',
          'Caja',
          'Marcas',
          'Paucara',
          'Pomacocha',
          'Rosario',
        ],
      },
      {
        nombre: 'Angaraes',
        distritos: [
          'Lircay',
          'Anchonga',
          'Callanmarca',
          'Ccochaccasa',
          'Chincho',
          'Congalla',
          'Huanca-Huanca',
          'Huayllay Grande',
          'Julcamarca',
          'San Antonio de Antaparco',
          'Santo Tomas de Pata',
          'Secclla',
        ],
      },
      {
        nombre: 'Castrovirreyna',
        distritos: [
          'Castrovirreyna',
          'Arma',
          'Aurahua',
          'Capillas',
          'Chupamarca',
          'Cocas',
          'Huachos',
          'Huamatambo',
          'Mollepampa',
          'San Juan',
          'Santa Ana',
          'Tantara',
          'Ticrapo',
        ],
      },
      {
        nombre: 'Churcampa',
        distritos: [
          'Churcampa',
          'Anco',
          'Chinchihuasi',
          'El Carmen',
          'La Merced',
          'Locroja',
          'Paucarbamba',
          'San Miguel de Mayocc',
          'San Pedro de Coris',
          'Pachamarca',
          'Cosme',
        ],
      },
      {
        nombre: 'Huaytara',
        distritos: [
          'Huaytara',
          'Ayavi',
          'Córdova',
          'Huayacundo Arma',
          'Laramarca',
          'Ocoyo',
          'Pilpichaca',
          'Querco',
          'Quito-Arma',
          'San Antonio de Cusicancha',
          'San Francisco de Sangayaico',
          'San Isidro',
          'Santiago de Chocorvos',
          'Santiago de Quirahuara',
          'Santo Domingo de Capillas',
          'Tambo',
        ],
      },
      {
        nombre: 'Tayacaja',
        distritos: [
          'Pampas',
          'Acostambo',
          'Acraquia',
          'Ahuaycha',
          'Colcabamba',
          'Daniel Hernández',
          'Huachocolpa',
          'Huaribamba',
          'Ñahuimpuquio',
          'Pazos',
          'Quishuar',
          'Salcabamba',
          'Salcahuasi',
          'San Marcos de Rocchac',
          'Surcubamba',
          'Tintay Puncu',
          'Quichuas',
          'Andaymarca',
          'Roble',
          'Pichos',
          'Santiago de Tucuma',
        ],
      },
    ],
  },
  {
    nombre: 'Huanuco',
    provincias: [
      {
        nombre: 'Huanuco',
        distritos: [
          'Huanuco',
          'Amarilis',
          'Chinchao',
          'Churubamba',
          'Margos',
          'Quisqui',
          'San Francisco de Cayran',
          'San Pedro de Chaulan',
          'Santa Maria del Valle',
          'Yarumayo',
          'Pillco Marca',
          'Yacus',
          'San Pablo de Pillao',
        ],
      },
      {
        nombre: 'Ambo',
        distritos: [
          'Ambo',
          'Cayna',
          'Colpas',
          'Conchamarca',
          'Huacar',
          'San Francisco',
          'San Rafael',
          'Tomay Kichwa',
        ],
      },
      {
        nombre: 'Dos de Mayo',
        distritos: [
          'La Union',
          'Chuquis',
          'Marías',
          'Pachas',
          'Quivilla',
          'Ripan',
          'Shunqui',
          'Sillapata',
          'Yanas',
        ],
      },
      {
        nombre: 'Huacaybamba',
        distritos: [
          'Huacaybamba',
          'Canchabamba',
          'Cochabamba',
          'Pinra',
        ],
      },
      {
        nombre: 'Huamalíes',
        distritos: [
          'Llata',
          'Arancay',
          'Chavin de Pariarca',
          'Jacas Grande',
          'Jircan',
          'Miraflores',
          'Monzón',
          'Punchao',
          'Puños',
          'Singa',
          'Tantamayo',
        ],
      },
      {
        nombre: 'Leoncio Prado',
        distritos: [
          'Rupa-Rupa',
          'Daniel Alomias Robles',
          'Hermílio Valdizan',
          'Jose Crespo y Castillo',
          'Luyando',
          'Mariano Damaso Beraun',
          'Pucayacu',
          'Castillo Grande',
          'Pueblo Nuevo',
          'Santo Domingo de Anda',
        ],
      },
      {
        nombre: 'Marañon',
        distritos: [
          'Huacrachuco',
          'Cholon',
          'San Buenaventura',
          'La Morada',
          'Santa Rosa de Alto Yanajanca',
        ],
      },
      {
        nombre: 'Pachitea',
        distritos: [
          'Panao',
          'Chaglla',
          'Molino',
          'Umari',
        ],
      },
      {
        nombre: 'Puerto Inca',
        distritos: [
          'Puerto Inca',
          'Codo del Pozuzo',
          'Honoria',
          'Tournavista',
          'Yuyapichis',
        ],
      },
      {
        nombre: 'Lauricocha',
        distritos: [
          'Jesus',
          'Baños',
          'Jivia',
          'Queropalca',
          'Rondos',
          'San Francisco de Asís',
          'San Miguel de Cauri',
        ],
      },
      {
        nombre: 'Yarowilca',
        distritos: [
          'Chavinillo',
          'Cahuac',
          'Chacabamba',
          'Aparicio Pomares',
          'Jacas Chico',
          'Obas',
          'Pampamarca',
          'Choras',
        ],
      },
    ],
  },
  {
    nombre: 'Ica',
    provincias: [
      {
        nombre: 'Ica',
        distritos: [
          'Ica',
          'La Tinguiña',
          'Los Aquijes',
          'Ocucaje',
          'Pachacutec',
          'Parcona',
          'Pueblo Nuevo',
          'Salas',
          'San Jose de los Molinos',
          'San Juan Bautista',
          'Santiago',
          'Subtanjalla',
          'Tate',
          'Yauca del Rosario',
        ],
      },
      {
        nombre: 'Chincha',
        distritos: [
          'Chincha Alta',
          'Alto Laran',
          'Chavin',
          'Chincha Baja',
          'El Carmen',
          'Grocio Prado',
          'Pueblo Nuevo',
          'San Juan de Yanac',
          'San Pedro de Huacarpana',
          'Sunampe',
          'Tambo de Mora',
        ],
      },
      {
        nombre: 'Nazca',
        distritos: [
          'Nazca',
          'Changuillo',
          'El Ingenio',
          'Marcona',
          'Vista Alegre',
        ],
      },
      {
        nombre: 'Palpa',
        distritos: [
          'Palpa',
          'Llipata',
          'Rio Grande',
          'Santa Cruz',
          'Tibillo',
        ],
      },
      {
        nombre: 'Pisco',
        distritos: [
          'Pisco',
          'Huancano',
          'Humay',
          'Independencia',
          'Paracas',
          'San Andrés',
          'San Clemente',
          'Tupac Amaru Inca',
        ],
      },
    ],
  },
  {
    nombre: 'Junín',
    provincias: [
      {
        nombre: 'Huancayo',
        distritos: [
          'Huancayo',
          'Carhuacallanga',
          'Chacapampa',
          'Chicche',
          'Chilca',
          'Chongos Alto',
          'Chupuro',
          'Colca',
          'Cullhuas',
          'El Tambo',
          'Huacrapuquio',
          'Hualhuas',
          'Huancan',
          'Huasicancha',
          'Huayucachi',
          'Ingenio',
          'Pariahuanca',
          'Pilcomayo',
          'Pucara',
          'Quichuay',
          'Quilcas',
          'San Agustín',
          'San Jerónimo de Tunan',
          'Saño',
          'Sapallanga',
          'Sicaya',
          'Santo Domingo de Acobamba',
          'Viques',
        ],
      },
      {
        nombre: 'Concepcion',
        distritos: [
          'Concepcion',
          'Aco',
          'Andamarca',
          'Chambara',
          'Cochas',
          'Comas',
          'Heroínas Toledo',
          'Manzanares',
          'Mariscal Castilla',
          'Matahuasi',
          'Mito',
          'Nueve de Julio',
          'Orcotuna',
          'San Jose de Quero',
          'Santa Rosa de Ocopa',
        ],
      },
      {
        nombre: 'Chanchamayo',
        distritos: [
          'Chanchamayo',
          'Perene',
          'Pichanaqui',
          'San Luis de Shuaro',
          'San Ramón',
          'Vitoc',
        ],
      },
      {
        nombre: 'Jauja',
        distritos: [
          'Jauja',
          'Acolla',
          'Apata',
          'Ataura',
          'Canchayllo',
          'Curicaca',
          'El Mantaro',
          'Huamali',
          'Huaripampa',
          'Huertas',
          'Janjaillo',
          'Julcan',
          'Leonor Ordóñez',
          'Llocllapampa',
          'Marco',
          'Masma',
          'Masma Chicche',
          'Molinos',
          'Monobamba',
          'Muqui',
          'Muquiyauyo',
          'Paca',
          'Paccha',
          'Pancan',
          'Parco',
          'Pomacancha',
          'Ricran',
          'San Lorenzo',
          'San Pedro de Chunan',
          'Sausa',
          'Sincos',
          'Tunan Marca',
          'Yauli',
          'Yauyos',
        ],
      },
      {
        nombre: 'Junín',
        distritos: [
          'Junín',
          'Carhuamayo',
          'Ondores',
          'Ulcumayo',
        ],
      },
      {
        nombre: 'Satipo',
        distritos: [
          'Satipo',
          'Coviriali',
          'Llaylla',
          'Mazamari',
          'Pampa Hermosa',
          'Pangoa',
          'Rio Negro',
          'Rio Tambo',
          'Vizcatan del Ene',
        ],
      },
      {
        nombre: 'Tarma',
        distritos: [
          'Tarma',
          'Acobamba',
          'Huaricolca',
          'Huasahuasi',
          'La Union',
          'Palca',
          'Palcamayo',
          'San Pedro de Cajas',
          'Tapo',
        ],
      },
      {
        nombre: 'Yauli',
        distritos: [
          'La Oroya',
          'Chacapalpa',
          'Huay-Huay',
          'Marcapomacocha',
          'Morococha',
          'Paccha',
          'Santa Barbara de Carhuacayan',
          'Santa Rosa de Sacco',
          'Suitucancha',
          'Yauli',
        ],
      },
      {
        nombre: 'Chupaca',
        distritos: [
          'Chupaca',
          'Ahuac',
          'Chongos Bajo',
          'Huachac',
          'Huamancaca Chico',
          'San Juan de Yscos',
          'San Juan de Jarpa',
          'Tres de Diciembre',
          'Yanacancha',
        ],
      },
    ],
  },
  {
    nombre: 'La Libertad',
    provincias: [
      {
        nombre: 'Trujillo',
        distritos: [
          'Trujillo',
          'El Porvenir',
          'Florencia de Mora',
          'Huanchaco',
          'La Esperanza',
          'Laredo',
          'Moche',
          'Poroto',
          'Salaverry',
          'Simbal',
          'Victor Larco Herrera',
        ],
      },
      {
        nombre: 'Ascope',
        distritos: [
          'Ascope',
          'Chicama',
          'Chocope',
          'Magdalena de Cao',
          'Paijan',
          'Rázuri',
          'Santiago de Cao',
          'Casa Grande',
        ],
      },
      {
        nombre: 'Bolivar',
        distritos: [
          'Bolivar',
          'Bambamarca',
          'Condormarca',
          'Longotea',
          'Uchumarca',
          'Ucuncha',
        ],
      },
      {
        nombre: 'Chepén',
        distritos: [
          'Chepén',
          'Pacanga',
          'Pueblo Nuevo',
        ],
      },
      {
        nombre: 'Julcan',
        distritos: [
          'Julcan',
          'Calamarca',
          'Carabamba',
          'Huaso',
        ],
      },
      {
        nombre: 'Otuzco',
        distritos: [
          'Otuzco',
          'Agallpampa',
          'Charat',
          'Huaranchal',
          'La Cuesta',
          'Mache',
          'Paranday',
          'Salpo',
          'Sinsicap',
          'Usquil',
        ],
      },
      {
        nombre: 'Pacasmayo',
        distritos: [
          'San Pedro de Lloc',
          'Guadalupe',
          'Jequetepeque',
          'Pacasmayo',
          'San Jose',
        ],
      },
      {
        nombre: 'Pataz',
        distritos: [
          'Tayabamba',
          'Buldibuyo',
          'Chillia',
          'Huancaspata',
          'Huaylillas',
          'Huayo',
          'Ongon',
          'Parcoy',
          'Pataz',
          'Pias',
          'Santiago de Challas',
          'Taurija',
          'Urpay',
        ],
      },
      {
        nombre: 'Sánchez Carrión',
        distritos: [
          'Huamachuco',
          'Chugay',
          'Cochorco',
          'Curgos',
          'Marcabal',
          'Sanagoran',
          'Sarin',
          'Sartimbamba',
        ],
      },
      {
        nombre: 'Santiago de Chuco',
        distritos: [
          'Santiago de Chuco',
          'Angasmarca',
          'Cachicadan',
          'Mollebamba',
          'Mollepata',
          'Quiruvilca',
          'Santa Cruz de Chuca',
          'Sitabamba',
        ],
      },
      {
        nombre: 'Gran Chimú',
        distritos: [
          'Cascas',
          'Lucma',
          'Compin',
          'Sayapullo',
        ],
      },
      {
        nombre: 'Virú',
        distritos: [
          'Virú',
          'Chao',
          'Guadalupito',
        ],
      },
    ],
  },
  {
    nombre: 'Lambayeque',
    provincias: [
      {
        nombre: 'Chiclayo',
        distritos: [
          'Chiclayo',
          'Chongoyape',
          'Eten',
          'Eten Puerto',
          'Jose Leonardo Ortiz',
          'La Victoria',
          'Lagunas',
          'Monsefu',
          'Nueva Arica',
          'Oyotun',
          'Picsi',
          'Pimentel',
          'Reque',
          'Santa Rosa',
          'Saña',
          'Cayalti',
          'Patapo',
          'Pomalca',
          'Pucala',
          'Tuman',
        ],
      },
      {
        nombre: 'Ferreñafe',
        distritos: [
          'Ferreñafe',
          'Cañaris',
          'Incahuasi',
          'Manuel Antonio Mesones Muro',
          'Pitipo',
          'Pueblo Nuevo',
        ],
      },
      {
        nombre: 'Lambayeque',
        distritos: [
          'Lambayeque',
          'Chochope',
          'Illimo',
          'Jayanca',
          'Mochumi',
          'Morrope',
          'Motupe',
          'Olmos',
          'Pacora',
          'Salas',
          'San Jose',
          'Tucume',
        ],
      },
    ],
  },
  {
    nombre: 'Lima',
    provincias: [
      {
        nombre: 'Lima',
        distritos: [
          'Lima',
          'Ancón',
          'Ate',
          'Barranco',
          'Breña',
          'Carabayllo',
          'Chaclacayo',
          'Chorrillos',
          'Cieneguilla',
          'Comas',
          'El Agustino',
          'Independencia',
          'Jesus Maria',
          'La Molina',
          'La Victoria',
          'Lince',
          'Los Olivos',
          'Lurigancho',
          'Lurin',
          'Magdalena del Mar',
          'Pueblo Libre',
          'Miraflores',
          'Pachacamac',
          'Pucusana',
          'Puente Piedra',
          'Punta Hermosa',
          'Punta Negra',
          'Rímac',
          'San Bartolo',
          'San Borja',
          'San Isidro',
          'San Juan de Lurigancho',
          'San Juan de Miraflores',
          'San Luis',
          'San Martín de Porres',
          'San Miguel',
          'Santa Anita',
          'Santa Maria del Mar',
          'Santa Rosa',
          'Santiago de Surco',
          'Surquillo',
          'Villa El Salvador',
          'Villa Maria del Triunfo',
        ],
      },
      {
        nombre: 'Barranca',
        distritos: [
          'Barranca',
          'Paramonga',
          'Pativilca',
          'Supe',
          'Supe Puerto',
        ],
      },
      {
        nombre: 'Cajatambo',
        distritos: [
          'Cajatambo',
          'Copa',
          'Gorgor',
          'Huancapon',
          'Manas',
        ],
      },
      {
        nombre: 'Canta',
        distritos: [
          'Canta',
          'Arahuay',
          'Huamantanga',
          'Huaros',
          'Lachaqui',
          'San Buenaventura',
          'Santa Rosa de Quives',
        ],
      },
      {
        nombre: 'Cañete',
        distritos: [
          'San Vicente de Cañete',
          'Asia',
          'Calango',
          'Cerro Azul',
          'Chilca',
          'Coayllo',
          'Imperial',
          'Lunahuana',
          'Mala',
          'Nuevo Imperial',
          'Pacaran',
          'Quilmana',
          'San Antonio',
          'San Luis',
          'Santa Cruz de Flores',
          'Zúñiga',
        ],
      },
      {
        nombre: 'Huaral',
        distritos: [
          'Huaral',
          'Atavillos Alto',
          'Atavillos Bajo',
          'Aucallama',
          'Chancay',
          'Ihuari',
          'Lampian',
          'Pacaraos',
          'San Miguel de Acos',
          'Santa Cruz de Andamarca',
          'Sumbilca',
          'Veintisiete de Noviembre',
        ],
      },
      {
        nombre: 'Huarochiri',
        distritos: [
          'Matucana',
          'Antioquia',
          'Callahuanca',
          'Carampoma',
          'Chicla',
          'Cuenca',
          'Huachupampa',
          'Huanza',
          'Huarochiri',
          'Lahuaytambo',
          'Langa',
          'Laraos',
          'Mariatana',
          'Ricardo Palma',
          'San Andrés de Tupicocha',
          'San Antonio',
          'San Bartolomé',
          'San Damian',
          'San Juan de Iris',
          'San Juan de Tantaranche',
          'San Lorenzo de Quinti',
          'San Mateo',
          'San Mateo de Otao',
          'San Pedro de Casta',
          'San Pedro de Huancayre',
          'Sangallaya',
          'Santa Cruz de Cocachacra',
          'Santa Eulalia',
          'Santiago de Anchucaya',
          'Santiago de Tuna',
          'Santo Domingo de los Olleros',
          'Surco',
        ],
      },
      {
        nombre: 'Huaura',
        distritos: [
          'Huacho',
          'Ambar',
          'Caleta de Carquin',
          'Checras',
          'Hualmay',
          'Huaura',
          'Leoncio Prado',
          'Paccho',
          'Santa Leonor',
          'Santa Maria',
          'Sayan',
          'Vegueta',
        ],
      },
      {
        nombre: 'Oyon',
        distritos: [
          'Oyon',
          'Andajes',
          'Caujul',
          'Cochamarca',
          'Navan',
          'Pachangara',
        ],
      },
      {
        nombre: 'Yauyos',
        distritos: [
          'Yauyos',
          'Alis',
          'Ayauca',
          'Ayaviri',
          'Azángaro',
          'Cacra',
          'Carania',
          'Catahuasi',
          'Chocos',
          'Cochas',
          'Colonia',
          'Hongos',
          'Huampara',
          'Huancaya',
          'Huangascar',
          'Huantan',
          'Huañec',
          'Laraos',
          'Lincha',
          'Madean',
          'Miraflores',
          'Omas',
          'Putinza',
          'Quinches',
          'Quinocay',
          'San Joaquín',
          'San Pedro de Pilas',
          'Tanta',
          'Tauripampa',
          'Tomas',
          'Tupe',
          'Viñac',
          'Vitis',
        ],
      },
    ],
  },
  {
    nombre: 'Loreto',
    provincias: [
      {
        nombre: 'Maynas',
        distritos: [
          'Iquitos',
          'Alto Nanay',
          'Fernando Lores',
          'Indiana',
          'Las Amazonas',
          'Mazan',
          'Napo',
          'Punchana',
          'Torres Causana',
          'Belén',
          'San Juan Bautista',
        ],
      },
      {
        nombre: 'Alto Amazonas',
        distritos: [
          'Yurimaguas',
          'Balsapuerto',
          'Jeberos',
          'Lagunas',
          'Santa Cruz',
          'Teniente Cesar López Rojas',
        ],
      },
      {
        nombre: 'Loreto',
        distritos: [
          'Nauta',
          'Parinari',
          'Tigre',
          'Trompeteros',
          'Urarinas',
        ],
      },
      {
        nombre: 'Mariscal Ramón Castilla',
        distritos: [
          'Ramón Castilla',
          'Pebas',
          'Yavari',
          'San Pablo',
        ],
      },
      {
        nombre: 'Requena',
        distritos: [
          'Requena',
          'Alto Tapiche',
          'Capelo',
          'Emilio San Martín',
          'Maquia',
          'Puinahua',
          'Saquena',
          'Soplin',
          'Tapiche',
          'Jenaro Herrera',
          'Yaquerana',
        ],
      },
      {
        nombre: 'Ucayali',
        distritos: [
          'Contamana',
          'Inahuaya',
          'Padre Marquez',
          'Pampa Hermosa',
          'Sarayacu',
          'Vargas Guerra',
        ],
      },
      {
        nombre: 'Datem del Marañon',
        distritos: [
          'Barranca',
          'Cahuapanas',
          'Manseriche',
          'Morona',
          'Pastaza',
          'Andoas',
        ],
      },
      {
        nombre: 'Putumayo',
        distritos: [
          'Putumayo',
          'Rosa Panduro',
          'Teniente Manuel Clavero',
          'Yaguas',
        ],
      },
    ],
  },
  {
    nombre: 'Madre de Dios',
    provincias: [
      {
        nombre: 'Tambopata',
        distritos: [
          'Tambopata',
          'Inambari',
          'Las Piedras',
          'Laberinto',
        ],
      },
      {
        nombre: 'Manu',
        distritos: [
          'Manu',
          'Fitzcarrald',
          'Madre de Dios',
          'Huepetuhe',
        ],
      },
      {
        nombre: 'Tahuamanu',
        distritos: [
          'Iñapari',
          'Iberia',
          'Tahuamanu',
        ],
      },
    ],
  },
  {
    nombre: 'Moquegua',
    provincias: [
      {
        nombre: 'Mariscal Nieto',
        distritos: [
          'Moquegua',
          'Carumas',
          'Cuchumbaya',
          'Samegua',
          'San Cristóbal',
          'Torata',
        ],
      },
      {
        nombre: 'General Sánchez Cerro',
        distritos: [
          'Omate',
          'Chojata',
          'Coalaque',
          'Ichuña',
          'La Capilla',
          'Lloque',
          'Matalaque',
          'Puquina',
          'Quinistaquillas',
          'Ubinas',
          'Yunga',
        ],
      },
      {
        nombre: 'Ilo',
        distritos: [
          'Ilo',
          'El Algarrobal',
          'Pacocha',
        ],
      },
    ],
  },
  {
    nombre: 'Pasco',
    provincias: [
      {
        nombre: 'Pasco',
        distritos: [
          'Chaupimarca',
          'Huachon',
          'Huariaca',
          'Huayllay',
          'Ninacaca',
          'Pallanchacra',
          'Paucartambo',
          'San Francisco de Asís de Yarusyacan',
          'Simon Bolivar',
          'Ticlacayan',
          'Tinyahuarco',
          'Vicco',
          'Yanacancha',
        ],
      },
      {
        nombre: 'Daniel Alcides Carrión',
        distritos: [
          'Yanahuanca',
          'Chacayan',
          'Goyllarisquizga',
          'Paucar',
          'San Pedro de Pillao',
          'Santa Ana de Tusi',
          'Tapuc',
          'Vilcabamba',
        ],
      },
      {
        nombre: 'Oxapampa',
        distritos: [
          'Oxapampa',
          'Chontabamba',
          'Huancabamba',
          'Palcazu',
          'Pozuzo',
          'Puerto Bermúdez',
          'Villa Rica',
          'Constitución',
        ],
      },
    ],
  },
  {
    nombre: 'Piura',
    provincias: [
      {
        nombre: 'Piura',
        distritos: [
          'Piura',
          'Castilla',
          'Catacaos',
          'Cura Mori',
          'El Tallan',
          'La Arena',
          'La Union',
          'Las Lomas',
          'Tambo Grande',
          '26 de Octubre',
        ],
      },
      {
        nombre: 'Ayabaca',
        distritos: [
          'Ayabaca',
          'Frias',
          'Jilili',
          'Lagunas',
          'Montero',
          'Pacaipampa',
          'Paimas',
          'Sapillica',
          'Sicchez',
          'Suyo',
        ],
      },
      {
        nombre: 'Huancabamba',
        distritos: [
          'Huancabamba',
          'Canchaque',
          'El Carmen de La Frontera',
          'Huarmaca',
          'Lalaquiz',
          'San Miguel de El Faique',
          'Sondor',
          'Sondorillo',
        ],
      },
      {
        nombre: 'Morropon',
        distritos: [
          'Chulucanas',
          'Buenos Aires',
          'Chalaco',
          'La Matanza',
          'Morropon',
          'Salitral',
          'San Juan de Bigote',
          'Santa Catalina de Mossa',
          'Santo Domingo',
          'Yamango',
        ],
      },
      {
        nombre: 'Paita',
        distritos: [
          'Paita',
          'Amotape',
          'Arenal',
          'Colan',
          'La Huaca',
          'Tamarindo',
          'Vichayal',
        ],
      },
      {
        nombre: 'Sullana',
        distritos: [
          'Sullana',
          'Bellavista',
          'Ignacio Escudero',
          'Lancones',
          'Marcavelica',
          'Miguel Checa',
          'Querecotillo',
          'Salitral',
        ],
      },
      {
        nombre: 'Talara',
        distritos: [
          'Pariñas',
          'El Alto',
          'La Brea',
          'Lobitos',
          'Los Organos',
          'Mancora',
        ],
      },
      {
        nombre: 'Sechura',
        distritos: [
          'Sechura',
          'Bellavista de La Union',
          'Bernal',
          'Cristo Nos Valga',
          'Vice',
          'Rinconada Llicuar',
        ],
      },
    ],
  },
  {
    nombre: 'Puno',
    provincias: [
      {
        nombre: 'Puno',
        distritos: [
          'Puno',
          'Acora',
          'Amantani',
          'Atuncolla',
          'Capachica',
          'Chucuito',
          'Coata',
          'Huata',
          'Mañazo',
          'Paucarcolla',
          'Pichacani',
          'Plateria',
          'San Antonio',
          'Tiquillaca',
          'Vilque',
        ],
      },
      {
        nombre: 'Azángaro',
        distritos: [
          'Azángaro',
          'Achaya',
          'Arapa',
          'Asillo',
          'Caminaca',
          'Chupa',
          'Jose Domingo Choquehuanca',
          'Muñani',
          'Potoni',
          'Saman',
          'San Anton',
          'San Jose',
          'San Juan de Salinas',
          'Santiago de Pupuja',
          'Tirapata',
        ],
      },
      {
        nombre: 'Carabaya',
        distritos: [
          'Macusani',
          'Ajoyani',
          'Ayapata',
          'Coasa',
          'Corani',
          'Crucero',
          'Ituata',
          'Ollachea',
          'San Gaban',
          'Usicayos',
        ],
      },
      {
        nombre: 'Chucuito',
        distritos: [
          'Juli',
          'Desaguadero',
          'Huacullani',
          'Kelluyo',
          'Pisacoma',
          'Pomata',
          'Zepita',
        ],
      },
      {
        nombre: 'El Collao',
        distritos: [
          'Ilave',
          'Capazo',
          'Pilcuyo',
          'Santa Rosa',
          'Conduriri',
        ],
      },
      {
        nombre: 'Huancane',
        distritos: [
          'Huancane',
          'Cojata',
          'Huatasani',
          'Inchupalla',
          'Pusi',
          'Rosaspata',
          'Taraco',
          'Vilque Chico',
        ],
      },
      {
        nombre: 'Lampa',
        distritos: [
          'Lampa',
          'Cabanilla',
          'Calapuja',
          'Nicasio',
          'Ocuviri',
          'Palca',
          'Paratia',
          'Pucara',
          'Santa Lucia',
          'Vilavila',
        ],
      },
      {
        nombre: 'Melgar',
        distritos: [
          'Ayaviri',
          'Antauta',
          'Cupi',
          'Llalli',
          'Macari',
          'Nuñoa',
          'Orurillo',
          'Santa Rosa',
          'Umachiri',
        ],
      },
      {
        nombre: 'Moho',
        distritos: [
          'Moho',
          'Conima',
          'Huayrapata',
          'Tilali',
        ],
      },
      {
        nombre: 'San Antonio de Putina',
        distritos: [
          'Putina',
          'Ananea',
          'Pedro Vilca Apaza',
          'Quilcapuncu',
          'Sina',
        ],
      },
      {
        nombre: 'San Román',
        distritos: [
          'Juliaca',
          'Cabana',
          'Cabanillas',
          'Caracoto',
          'San Miguel',
        ],
      },
      {
        nombre: 'Sandia',
        distritos: [
          'Sandia',
          'Cuyocuyo',
          'Limbani',
          'Patambuco',
          'Phara',
          'Quiaca',
          'San Juan del Oro',
          'Yanahuaya',
          'Alto Inambari',
          'San Pedro de Putina Punco',
        ],
      },
      {
        nombre: 'Yunguyo',
        distritos: [
          'Yunguyo',
          'Anapia',
          'Copani',
          'Cuturapi',
          'Ollaraya',
          'Tinicachi',
          'Unicachi',
        ],
      },
    ],
  },
  {
    nombre: 'San Martín',
    provincias: [
      {
        nombre: 'Moyobamba',
        distritos: [
          'Moyobamba',
          'Calzada',
          'Habana',
          'Jepelacio',
          'Soritor',
          'Yantalo',
        ],
      },
      {
        nombre: 'San Martín',
        distritos: [
          'Bellavista',
          'Alto Biavo',
          'Bajo Biavo',
          'Huallaga',
          'San Pablo',
          'San Rafael',
        ],
      },
      {
        nombre: 'El Dorado',
        distritos: [
          'San Jose de Sisa',
          'Agua Blanca',
          'San Martín',
          'Santa Rosa',
          'Shatoja',
        ],
      },
      {
        nombre: 'Huallaga',
        distritos: [
          'Saposoa',
          'Alto Saposoa',
          'El Eslabón',
          'Piscoyacu',
          'Sacanche',
          'Tingo de Saposoa',
        ],
      },
      {
        nombre: 'Lamas',
        distritos: [
          'Lamas',
          'Alonso de Alvarado',
          'Barranquita',
          'Caynarachi',
          'Cuñumbuqui',
          'Pinto Recodo',
          'Rumisapa',
          'San Roque de Cumbaza',
          'Shanao',
          'Tabalosos',
          'Zapatero',
        ],
      },
      {
        nombre: 'Mariscal Cáceres',
        distritos: [
          'Juanjuí',
          'Campanilla',
          'Huicungo',
          'Pachiza',
          'Pajarillo',
        ],
      },
      {
        nombre: 'Picota',
        distritos: [
          'Picota',
          'Buenos Aires',
          'Caspisapa',
          'Pilluana',
          'Pucacaca',
          'San Cristóbal',
          'San Hilarión',
          'Shamboyacu',
          'Tingo de Ponasa',
          'Tres Unidos',
        ],
      },
      {
        nombre: 'Rioja',
        distritos: [
          'Rioja',
          'Awajun',
          'Elías Soplin Vargas',
          'Nueva Cajamarca',
          'Pardo Miguel',
          'Posic',
          'San Fernando',
          'Yorongos',
          'Yuracyacu',
        ],
      },
      {
        nombre: 'Tarapoto',
        distritos: [
          'Tarapoto',
          'Alberto Leveau',
          'Cacatachi',
          'Chazuta',
          'Chipurana',
          'El Porvenir',
          'Huimbayoc',
          'Juan Guerra',
          'La Banda de Shilcayo',
          'Morales',
          'Papaplaya',
          'San Antonio',
          'Sauce',
          'Shapaja',
        ],
      },
      {
        nombre: 'Tocache',
        distritos: [
          'Tocache',
          'Nuevo Progreso',
          'Polvora',
          'Shunte',
          'Uchiza',
        ],
      },
    ],
  },
  {
    nombre: 'Tacna',
    provincias: [
      {
        nombre: 'Tacna',
        distritos: [
          'Tacna',
          'Alto de La Alianza',
          'Calana',
          'Ciudad Nueva',
          'Inclan',
          'Pachia',
          'Palca',
          'Pocollay',
          'Sama',
          'Coronel Gregorio Albarracín Lanchipa',
          'La Yarada-Los Palos',
        ],
      },
      {
        nombre: 'Candarave',
        distritos: [
          'Candarave',
          'Cairani',
          'Camilaca',
          'Curibaya',
          'Huanuara',
          'Quilahuani',
        ],
      },
      {
        nombre: 'Jorge Basadre',
        distritos: [
          'Locumba',
          'Ilabaya',
          'Ite',
        ],
      },
      {
        nombre: 'Tarata',
        distritos: [
          'Tarata',
          'Héroes Albarracín',
          'Estique',
          'Estique-Pampa',
          'Sitajara',
          'Susapaya',
          'Tarucachi',
          'Ticaco',
        ],
      },
    ],
  },
  {
    nombre: 'Tumbes',
    provincias: [
      {
        nombre: 'Tumbes',
        distritos: [
          'Tumbes',
          'Corrales',
          'La Cruz',
          'Pampas de Hospital',
          'San Jacinto',
          'San Juan de La Virgen',
        ],
      },
      {
        nombre: 'Contralmirante Villa',
        distritos: [
          'Zorritos',
          'Casitas',
          'Canoas de Punta Sal',
        ],
      },
      {
        nombre: 'Zarumilla',
        distritos: [
          'Zarumilla',
          'Aguas Verdes',
          'Matapalo',
          'Papayal',
        ],
      },
    ],
  },
  {
    nombre: 'Ucayali',
    provincias: [
      {
        nombre: 'Coronel Portillo',
        distritos: [
          'Calleria',
          'Campoverde',
          'Iparia',
          'Masisea',
          'Yarinacocha',
          'Nueva Requena',
          'Manantay',
        ],
      },
      {
        nombre: 'Atalaya',
        distritos: [
          'Raymondi',
          'Sepahua',
          'Tahuania',
          'Yurua',
        ],
      },
      {
        nombre: 'Padre Abad',
        distritos: [
          'Padre Abad',
          'Irazola',
          'Curimana',
          'Neshuya',
          'Alexander Von Humboldt',
        ],
      },
      {
        nombre: 'Purús',
        distritos: [
          'Purús',
        ],
      },
    ],
  },
];

export function getDepartamentos(): string[] {
  return UBIGEO.map(d => d.nombre);
}

export function getProvincias(departamento: string): string[] {
  const dep = UBIGEO.find(d => d.nombre === departamento);
  return dep ? dep.provincias.map(p => p.nombre) : [];
}

export function getDistritos(departamento: string, provincia: string): string[] {
  const dep = UBIGEO.find(d => d.nombre === departamento);
  if (!dep) return [];
  const prov = dep.provincias.find(p => p.nombre === provincia);
  return prov ? prov.distritos : [];
}
