import { AgendaEvent } from './types';

export const MOCK_EVENTS: AgendaEvent[] = [
    {
        id: 'order_1',
        type: 'order',
        date: new Date().toISOString().split('T')[0],
        time: '10:00',
        title: 'LYR-20260531-1234',
        subtitle: 'Juan Perez',
        status: 'paid',
        payment_status: 'paid',
        total: 150.00,
        customer_name: 'Juan Perez',
        customer_email: 'juan@example.com',
        customer_phone: '999888777',
        items_summary: 'Producto Demo + 2 más',
        order_id: 1,
        order_number: 'LYR-20260531-1234',
        order_status: 'confirmed',
        payment_method: 'Tarjeta',
        paid_at: new Date().toISOString(),
        shipping_address: 'Av. Larco 456, Miraflores',
        shipping_city: 'Lima',
        shipping_type: 'delivery',
        subtotal: 120.00,
        shipping_cost: 20.00,
        tax_amount: 10.00,
        discount_amount: 0,
        items: [
            { product_name: 'Producto Demo', quantity: 2, unit_price: 50, line_total: 100, image_url: null },
            { product_name: 'Otro Producto', quantity: 1, unit_price: 20, line_total: 20, image_url: null },
        ],
        shipment: {
            carrier: 'Olva Courier',
            tracking_number: 'OLV-987654',
            tracking_url: null,
            status: 'in_transit',
            shipped_at: new Date().toISOString(),
            delivered_at: null,
        },
    },
    {
        id: 'booking_1',
        type: 'service',
        date: new Date().toISOString().split('T')[0],
        time: '11:00',
        title: 'Evaluación Nutricional',
        subtitle: 'Carlos Rodriguez',
        status: 'confirmed',
        payment_status: 'paid',
        total: 80.00,
        customer_name: 'Carlos Rodriguez',
        customer_email: 'carlos@example.com',
        customer_phone: '999111222',
        service_name: 'Evaluación Nutricional',
        booking_id: 1,
        service_id: 1,
        duration_minutes: 45,
        payment_method: 'Tarjeta',
        notes: 'Cliente prefiere atención virtual',
        appointment_date: new Date().toISOString(),
        end_time: '11:45',
        specialist: {
            id: 1,
            nombres: 'Dra. Maria',
            apellidos: 'Garcia',
            especialidad: 'Nutrición Deportiva',
            foto: null,
        },
    },
];
