import type { Plan, ButtonColors, SubscriptionInfo, ExpirationWarning } from './types';

export const mockPlans: Record<string, Plan> = {
    basic: {
        id: 'basic',
        name: 'EMPRENDE',
        price: 0,
        priceAnnual: 0,
        period: '/mes',
        periodAnnual: '/año',
        currency: 'S/',
        usePriceMode: false,
        priceText: '',
        priceSubtext: '',
        description: 'Plan gratuito para empezar tu tienda en LYRIUM Biomarketplace. Incluye todas las herramientas esenciales.',
        badge: 'PLAN EMPRENDE',
        cssColor: '#9cb04e',
        accentColor: '#7d9940',
        bgImage: '',
        bgImageFit: 'cover',
        bgImagePosition: 'center',
        showBgInCard: false,
        requiresPayment: false,
        subscribeButtonText: 'Suscribirse',
        trialSuccessTitle: '¡Has activado el plan gratuito!',
        trialSuccessMessage: 'Tu plan EMPRENDE está activo. Comienza a vender en LYRIUM.',
        trialWaitMessage: 'Tu plan se activará automáticamente.',
        enableClaimLock: false,
        claimedButtonText: '',
        claimedWarningText: '',
        timelineIcon: 'shield',
        compactVisibleCount: 5,
        isActive: true,
        orden: 1,
        claimMonths: 1,
        features: [
            { text: 'Exposición de productos al buscar en LYRIUM', active: true },
            { text: 'Espacio propio para personalizar tu tienda', active: true },
            { text: 'Logotipo, información y banner publicitario', active: true },
            { text: 'Exposición de productos y servicios', active: true },
            { text: 'Redes sociales en tu tienda', active: true },
        ],
        detailedBenefits: [
            { emoji: '🔍', title: 'Exposición de productos al buscar', description: 'Tus productos aparecerán en los resultados de búsqueda de LYRIUM.', color: '#9cb04e' },
            { emoji: '🏪', title: 'Espacio propio para tu tienda', description: 'Obtén una tienda virtual completamente personalizable.', color: '#9cb04e' },
            { emoji: '🎨', title: 'Logotipo y banner publicitario', description: 'Sube tu logotipo y configura un banner atractivo.', color: '#9cb04e' },
        ]
    },
    standard: {
        id: 'standard',
        name: 'CRECE',
        price: 7.99,
        priceAnnual: 95.88,
        period: '/mes',
        periodAnnual: '/año',
        currency: 'S/',
        usePriceMode: false,
        priceText: '',
        priceSubtext: '',
        description: 'Haz crecer tu tienda con herramientas avanzadas, capacitaciones y atención preferencial.',
        badge: 'MÁS POPULAR',
        cssColor: '#64c695',
        accentColor: '#4da978',
        bgImage: '',
        bgImageFit: 'cover',
        bgImagePosition: 'center',
        showBgInCard: false,
        requiresPayment: true,
        subscribeButtonText: 'Suscribirse',
        trialSuccessTitle: '¡Solicitud enviada!',
        trialSuccessMessage: 'Tu solicitud para el plan CRECE ha sido enviada.',
        trialWaitMessage: 'Tu pago está siendo procesado.',
        enableClaimLock: false,
        claimedButtonText: '',
        claimedWarningText: '',
        timelineIcon: 'layers',
        compactVisibleCount: 5,
        isActive: true,
        orden: 2,
        claimMonths: 1,
        features: [
            { text: 'Todo lo del plan EMPRENDE', active: true },
            { text: 'Logo en banners principales de LYRIUM', active: true },
            { text: 'Capacitaciones online en postventa', active: true },
            { text: 'Medalla de producto recomendado por LYRIUM', active: true },
            { text: 'Atención preferencial por LYRIUM', active: true },
        ],
        detailedBenefits: [
            { emoji: '✅', title: 'Todo lo del plan EMPRENDE', description: 'Incluye absolutamente todos los beneficios del plan EMPRENDE.', color: '#64c695' },
            { emoji: '🏆', title: 'Logo en banners principales', description: 'Tu logotipo en los banners más visibles de la plataforma.', color: '#64c695' },
            { emoji: '🎓', title: 'Capacitaciones online en postventa', description: 'Sesiones enfocadas en estrategias de postventa.', color: '#64c695' },
        ]
    },
    premium: {
        id: 'premium',
        name: 'ESPECIAL',
        price: 89.90,
        priceAnnual: 863.00,
        period: '/mes',
        periodAnnual: '/año',
        currency: 'S/',
        usePriceMode: false,
        priceText: '',
        priceSubtext: '',
        description: 'La experiencia máxima en LYRIUM Biomarketplace. Todo incluido con soporte dedicado.',
        badge: 'PLAN ESPECIAL',
        cssColor: '#499bbf',
        accentColor: '#357fa3',
        bgImage: '',
        bgImageFit: 'cover',
        bgImagePosition: 'center',
        showBgInCard: false,
        requiresPayment: true,
        subscribeButtonText: 'Reclamar prueba gratuita',
        trialSuccessTitle: '¡Ha reclamo con éxito el plan ESPECIAL!',
        trialSuccessMessage: 'Tu plan se activará en breve.',
        trialWaitMessage: 'Tu plan se activará automáticamente.',
        enableClaimLock: true,
        claimedButtonText: '',
        claimedWarningText: 'Este plan ya ha sido reclamado con anterioriedad',
        timelineIcon: 'star',
        compactVisibleCount: 5,
        isActive: true,
        orden: 3,
        claimMonths: 1,
        features: [
            { text: 'Todo lo del plan CRECE', active: true },
            { text: 'Atención preferencial prioritaria', active: true },
            { text: 'Asesorías de seguimiento comercial avanzadas', active: true },
            { text: 'Capacitaciones avanzadas del dashboard', active: true },
            { text: 'Merchandising y material especial postventa', active: true },
        ],
        detailedBenefits: [
            { emoji: '✅', title: 'Todo lo del plan CRECE', description: 'Incluye absolutamente todos los beneficios anteriores.', color: '#499bbf' },
            { emoji: '⚡', title: 'Atención preferencial prioritaria', description: 'Soporte prioritario con tiempos de respuesta reducidos.', color: '#499bbf' },
            { emoji: '📈', title: 'Asesorías avanzadas', description: 'Un asesor te acompañará personalmente.', color: '#499bbf' },
        ]
    }
};

export const mockButtonColors: ButtonColors = {
    subscribeBg: '#3b82f6',
    subscribeColor: '#ffffff',
    currentBg: '#e5e7eb',
    currentColor: '#9ca3af',
    lockedBg: '#e5e7eb',
    lockedColor: '#9ca3af',
    warningColor: '#f59e0b'
};

export const mockSubscription: SubscriptionInfo = {
    plan: 'basic',
    months: 1,
    planId: 'basic',
    startDate: new Date().toISOString(),
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active'
};

export const mockExpirationWarning: ExpirationWarning = {
    porVencer: false,
    dias: 0,
    fechaVencimiento: ''
};
